// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/transactions/transactions.proto

package go_micro_service_transactions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Transactions service

func NewTransactionsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Transactions service

type TransactionsService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Transactions_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Transactions_PingPongService, error)
}

type transactionsService struct {
	c    client.Client
	name string
}

func NewTransactionsService(name string, c client.Client) TransactionsService {
	return &transactionsService{
		c:    c,
		name: name,
	}
}

func (c *transactionsService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Transactions.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Transactions_StreamService, error) {
	req := c.c.NewRequest(c.name, "Transactions.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &transactionsServiceStream{stream}, nil
}

type Transactions_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type transactionsServiceStream struct {
	stream client.Stream
}

func (x *transactionsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *transactionsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *transactionsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *transactionsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *transactionsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionsService) PingPong(ctx context.Context, opts ...client.CallOption) (Transactions_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Transactions.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &transactionsServicePingPong{stream}, nil
}

type Transactions_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type transactionsServicePingPong struct {
	stream client.Stream
}

func (x *transactionsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *transactionsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *transactionsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *transactionsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *transactionsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *transactionsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Transactions service

type TransactionsHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Transactions_StreamStream) error
	PingPong(context.Context, Transactions_PingPongStream) error
}

func RegisterTransactionsHandler(s server.Server, hdlr TransactionsHandler, opts ...server.HandlerOption) error {
	type transactions interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Transactions struct {
		transactions
	}
	h := &transactionsHandler{hdlr}
	return s.Handle(s.NewHandler(&Transactions{h}, opts...))
}

type transactionsHandler struct {
	TransactionsHandler
}

func (h *transactionsHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TransactionsHandler.Call(ctx, in, out)
}

func (h *transactionsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TransactionsHandler.Stream(ctx, m, &transactionsStreamStream{stream})
}

type Transactions_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type transactionsStreamStream struct {
	stream server.Stream
}

func (x *transactionsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *transactionsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *transactionsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *transactionsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *transactionsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *transactionsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TransactionsHandler.PingPong(ctx, &transactionsPingPongStream{stream})
}

type Transactions_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type transactionsPingPongStream struct {
	stream server.Stream
}

func (x *transactionsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *transactionsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *transactionsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *transactionsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *transactionsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *transactionsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
