// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/profiles/profiles.proto

package go_micro_service_queries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Queries service

func NewQueriesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Queries service

type QueriesService interface {
	GetUserState(ctx context.Context, in *UserStateRequest, opts ...client.CallOption) (*UserStateResponse, error)
	GetAccountDetail(ctx context.Context, in *AccountDetailRequest, opts ...client.CallOption) (*AccountResponseType, error)
}

type queriesService struct {
	c    client.Client
	name string
}

func NewQueriesService(name string, c client.Client) QueriesService {
	return &queriesService{
		c:    c,
		name: name,
	}
}

func (c *queriesService) GetUserState(ctx context.Context, in *UserStateRequest, opts ...client.CallOption) (*UserStateResponse, error) {
	req := c.c.NewRequest(c.name, "Queries.GetUserState", in)
	out := new(UserStateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queriesService) GetAccountDetail(ctx context.Context, in *AccountDetailRequest, opts ...client.CallOption) (*AccountResponseType, error) {
	req := c.c.NewRequest(c.name, "Queries.GetAccountDetail", in)
	out := new(AccountResponseType)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Queries service

type QueriesHandler interface {
	GetUserState(context.Context, *UserStateRequest, *UserStateResponse) error
	GetAccountDetail(context.Context, *AccountDetailRequest, *AccountResponseType) error
}

func RegisterQueriesHandler(s server.Server, hdlr QueriesHandler, opts ...server.HandlerOption) error {
	type queries interface {
		GetUserState(ctx context.Context, in *UserStateRequest, out *UserStateResponse) error
		GetAccountDetail(ctx context.Context, in *AccountDetailRequest, out *AccountResponseType) error
	}
	type Queries struct {
		queries
	}
	h := &queriesHandler{hdlr}
	return s.Handle(s.NewHandler(&Queries{h}, opts...))
}

type queriesHandler struct {
	QueriesHandler
}

func (h *queriesHandler) GetUserState(ctx context.Context, in *UserStateRequest, out *UserStateResponse) error {
	return h.QueriesHandler.GetUserState(ctx, in, out)
}

func (h *queriesHandler) GetAccountDetail(ctx context.Context, in *AccountDetailRequest, out *AccountResponseType) error {
	return h.QueriesHandler.GetAccountDetail(ctx, in, out)
}
