version: '3.3'

services:

  server:
    command: server
    image: micro/micro
    container_name: server
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

  projects-srv:
    build: lagerist.io/srv/projects
    container_name: projects-srv
    command: /root/projects

  entities-srv:
    build: lagerist.io/srv/entities
    container_name: entities-srv
    command: /root/entities

  processing-srv:
    build: lagerist.io/srv/processing
    container_name: processing-srv
    command: /root/processing
