// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/projects/projects.proto

package go_micro_service_projects

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Projects service

func NewProjectsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Projects service

type ProjectsService interface {
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Projects_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Projects_PingPongService, error)
}

type projectsService struct {
	c    client.Client
	name string
}

func NewProjectsService(name string, c client.Client) ProjectsService {
	return &projectsService{
		c:    c,
		name: name,
	}
}

func (c *projectsService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Projects.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Projects_StreamService, error) {
	req := c.c.NewRequest(c.name, "Projects.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &projectsServiceStream{stream}, nil
}

type Projects_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type projectsServiceStream struct {
	stream client.Stream
}

func (x *projectsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *projectsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *projectsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *projectsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *projectsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *projectsService) PingPong(ctx context.Context, opts ...client.CallOption) (Projects_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Projects.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &projectsServicePingPong{stream}, nil
}

type Projects_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type projectsServicePingPong struct {
	stream client.Stream
}

func (x *projectsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *projectsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *projectsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *projectsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *projectsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *projectsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Projects service

type ProjectsHandler interface {
	Create(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Projects_StreamStream) error
	PingPong(context.Context, Projects_PingPongStream) error
}

func RegisterProjectsHandler(s server.Server, hdlr ProjectsHandler, opts ...server.HandlerOption) error {
	type projects interface {
		Create(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Projects struct {
		projects
	}
	h := &projectsHandler{hdlr}
	return s.Handle(s.NewHandler(&Projects{h}, opts...))
}

type projectsHandler struct {
	ProjectsHandler
}

func (h *projectsHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.ProjectsHandler.Create(ctx, in, out)
}

func (h *projectsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProjectsHandler.Stream(ctx, m, &projectsStreamStream{stream})
}

type Projects_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type projectsStreamStream struct {
	stream server.Stream
}

func (x *projectsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *projectsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *projectsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *projectsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *projectsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *projectsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ProjectsHandler.PingPong(ctx, &projectsPingPongStream{stream})
}

type Projects_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type projectsPingPongStream struct {
	stream server.Stream
}

func (x *projectsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *projectsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *projectsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *projectsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *projectsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *projectsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
