// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/entities/entities.proto

package go_micro_service_entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Entities service

func NewEntitiesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Entities service

type EntitiesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Entities_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Entities_PingPongService, error)
}

type entitiesService struct {
	c    client.Client
	name string
}

func NewEntitiesService(name string, c client.Client) EntitiesService {
	return &entitiesService{
		c:    c,
		name: name,
	}
}

func (c *entitiesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Entities.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitiesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Entities_StreamService, error) {
	req := c.c.NewRequest(c.name, "Entities.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &entitiesServiceStream{stream}, nil
}

type Entities_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type entitiesServiceStream struct {
	stream client.Stream
}

func (x *entitiesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *entitiesServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *entitiesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *entitiesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *entitiesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *entitiesService) PingPong(ctx context.Context, opts ...client.CallOption) (Entities_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Entities.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &entitiesServicePingPong{stream}, nil
}

type Entities_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type entitiesServicePingPong struct {
	stream client.Stream
}

func (x *entitiesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *entitiesServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *entitiesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *entitiesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *entitiesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *entitiesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Entities service

type EntitiesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Entities_StreamStream) error
	PingPong(context.Context, Entities_PingPongStream) error
}

func RegisterEntitiesHandler(s server.Server, hdlr EntitiesHandler, opts ...server.HandlerOption) error {
	type entities interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Entities struct {
		entities
	}
	h := &entitiesHandler{hdlr}
	return s.Handle(s.NewHandler(&Entities{h}, opts...))
}

type entitiesHandler struct {
	EntitiesHandler
}

func (h *entitiesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.EntitiesHandler.Call(ctx, in, out)
}

func (h *entitiesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.EntitiesHandler.Stream(ctx, m, &entitiesStreamStream{stream})
}

type Entities_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type entitiesStreamStream struct {
	stream server.Stream
}

func (x *entitiesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *entitiesStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *entitiesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *entitiesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *entitiesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *entitiesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.EntitiesHandler.PingPong(ctx, &entitiesPingPongStream{stream})
}

type Entities_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type entitiesPingPongStream struct {
	stream server.Stream
}

func (x *entitiesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *entitiesPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *entitiesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *entitiesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *entitiesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *entitiesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
