// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/processing/processing.proto

package go_micro_service_processing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Processing service

func NewProcessingEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Processing service

type ProcessingService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Processing_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Processing_PingPongService, error)
}

type processingService struct {
	c    client.Client
	name string
}

func NewProcessingService(name string, c client.Client) ProcessingService {
	return &processingService{
		c:    c,
		name: name,
	}
}

func (c *processingService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Processing.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Processing_StreamService, error) {
	req := c.c.NewRequest(c.name, "Processing.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &processingServiceStream{stream}, nil
}

type Processing_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type processingServiceStream struct {
	stream client.Stream
}

func (x *processingServiceStream) Close() error {
	return x.stream.Close()
}

func (x *processingServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *processingServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *processingServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *processingServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *processingService) PingPong(ctx context.Context, opts ...client.CallOption) (Processing_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Processing.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &processingServicePingPong{stream}, nil
}

type Processing_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type processingServicePingPong struct {
	stream client.Stream
}

func (x *processingServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *processingServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *processingServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *processingServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *processingServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *processingServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Processing service

type ProcessingHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Processing_StreamStream) error
	PingPong(context.Context, Processing_PingPongStream) error
}

func RegisterProcessingHandler(s server.Server, hdlr ProcessingHandler, opts ...server.HandlerOption) error {
	type processing interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Processing struct {
		processing
	}
	h := &processingHandler{hdlr}
	return s.Handle(s.NewHandler(&Processing{h}, opts...))
}

type processingHandler struct {
	ProcessingHandler
}

func (h *processingHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ProcessingHandler.Call(ctx, in, out)
}

func (h *processingHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProcessingHandler.Stream(ctx, m, &processingStreamStream{stream})
}

type Processing_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type processingStreamStream struct {
	stream server.Stream
}

func (x *processingStreamStream) Close() error {
	return x.stream.Close()
}

func (x *processingStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *processingStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *processingStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *processingStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *processingHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ProcessingHandler.PingPong(ctx, &processingPingPongStream{stream})
}

type Processing_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type processingPingPongStream struct {
	stream server.Stream
}

func (x *processingPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *processingPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *processingPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *processingPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *processingPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *processingPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
