// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/processing.proto

package processing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Processing service

func NewProcessingEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Processing service

type ProcessingService interface {
	ProcessingEntity(ctx context.Context, in *ProcessingEntityRequest, opts ...client.CallOption) (*ProcessingEntityResponse, error)
}

type processingService struct {
	c    client.Client
	name string
}

func NewProcessingService(name string, c client.Client) ProcessingService {
	return &processingService{
		c:    c,
		name: name,
	}
}

func (c *processingService) ProcessingEntity(ctx context.Context, in *ProcessingEntityRequest, opts ...client.CallOption) (*ProcessingEntityResponse, error) {
	req := c.c.NewRequest(c.name, "Processing.ProcessingEntity", in)
	out := new(ProcessingEntityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Processing service

type ProcessingHandler interface {
	ProcessingEntity(context.Context, *ProcessingEntityRequest, *ProcessingEntityResponse) error
}

func RegisterProcessingHandler(s server.Server, hdlr ProcessingHandler, opts ...server.HandlerOption) error {
	type processing interface {
		ProcessingEntity(ctx context.Context, in *ProcessingEntityRequest, out *ProcessingEntityResponse) error
	}
	type Processing struct {
		processing
	}
	h := &processingHandler{hdlr}
	return s.Handle(s.NewHandler(&Processing{h}, opts...))
}

type processingHandler struct {
	ProcessingHandler
}

func (h *processingHandler) ProcessingEntity(ctx context.Context, in *ProcessingEntityRequest, out *ProcessingEntityResponse) error {
	return h.ProcessingHandler.ProcessingEntity(ctx, in, out)
}
