// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/entities.proto

package entities

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Entities service

func NewEntitiesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Entities service

type EntitiesService interface {
	CreateEntity(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type entitiesService struct {
	c    client.Client
	name string
}

func NewEntitiesService(name string, c client.Client) EntitiesService {
	return &entitiesService{
		c:    c,
		name: name,
	}
}

func (c *entitiesService) CreateEntity(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Entities.CreateEntity", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Entities service

type EntitiesHandler interface {
	CreateEntity(context.Context, *Request, *Response) error
}

func RegisterEntitiesHandler(s server.Server, hdlr EntitiesHandler, opts ...server.HandlerOption) error {
	type entities interface {
		CreateEntity(ctx context.Context, in *Request, out *Response) error
	}
	type Entities struct {
		entities
	}
	h := &entitiesHandler{hdlr}
	return s.Handle(s.NewHandler(&Entities{h}, opts...))
}

type entitiesHandler struct {
	EntitiesHandler
}

func (h *entitiesHandler) CreateEntity(ctx context.Context, in *Request, out *Response) error {
	return h.EntitiesHandler.CreateEntity(ctx, in, out)
}
