const fs = require('fs');
const path = require('path');

module.exports.getComment = fs.readFileSync(path.join(__dirname, 'getComment.gql'), 'utf8');
module.exports.queryComment = fs.readFileSync(path.join(__dirname, 'queryComment.gql'), 'utf8');
module.exports.getTag = fs.readFileSync(path.join(__dirname, 'getTag.gql'), 'utf8');
module.exports.queryTag = fs.readFileSync(path.join(__dirname, 'queryTag.gql'), 'utf8');
module.exports.getTask = fs.readFileSync(path.join(__dirname, 'getTask.gql'), 'utf8');
module.exports.queryTask = fs.readFileSync(path.join(__dirname, 'queryTask.gql'), 'utf8');
module.exports.getColumn = fs.readFileSync(path.join(__dirname, 'getColumn.gql'), 'utf8');
module.exports.queryColumn = fs.readFileSync(path.join(__dirname, 'queryColumn.gql'), 'utf8');
module.exports.getBoard = fs.readFileSync(path.join(__dirname, 'getBoard.gql'), 'utf8');
module.exports.queryBoard = fs.readFileSync(path.join(__dirname, 'queryBoard.gql'), 'utf8');
module.exports.getWorker = fs.readFileSync(path.join(__dirname, 'getWorker.gql'), 'utf8');
module.exports.queryWorker = fs.readFileSync(path.join(__dirname, 'queryWorker.gql'), 'utf8');
module.exports.getUser = fs.readFileSync(path.join(__dirname, 'getUser.gql'), 'utf8');
module.exports.queryUser = fs.readFileSync(path.join(__dirname, 'queryUser.gql'), 'utf8');
module.exports.getProject = fs.readFileSync(path.join(__dirname, 'getProject.gql'), 'utf8');
module.exports.queryProject = fs.readFileSync(path.join(__dirname, 'queryProject.gql'), 'utf8');
