const Constants = {
  GET_ACCOUNT: 'GET_ACCOUNT',
  INIT_ACCOUNTS: 'INIT_ACCOUNTS',
  INIT_ACCOUNTS_SUCCESS: 'INIT_ACCOUNTS_SUCCESS',
  INIT_ACCOUNTS_ERROR: 'INIT_ACCOUNTS_ERROR',
  INIT_ACCOUNT_DETAIL: 'INIT_ACCOUNT_DETAIL',
  INIT_ACCOUNT_DETAIL_SUCCESS: 'INIT_ACCOUNT_DETAIL_SUCCESS',
  INIT_ACCOUNT_DETAIL_ERROR: 'INIT_ACCOUNT_DETAIL_ERROR',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  GET_USER: 'GET_USER',
}

export default Constants;
