// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/queries/queries.proto

package go_micro_service_queries

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Queries service

func NewQueriesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Queries service

type QueriesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Queries_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Queries_PingPongService, error)
}

type queriesService struct {
	c    client.Client
	name string
}

func NewQueriesService(name string, c client.Client) QueriesService {
	return &queriesService{
		c:    c,
		name: name,
	}
}

func (c *queriesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Queries.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queriesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Queries_StreamService, error) {
	req := c.c.NewRequest(c.name, "Queries.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &queriesServiceStream{stream}, nil
}

type Queries_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type queriesServiceStream struct {
	stream client.Stream
}

func (x *queriesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *queriesServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *queriesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *queriesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *queriesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queriesService) PingPong(ctx context.Context, opts ...client.CallOption) (Queries_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Queries.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &queriesServicePingPong{stream}, nil
}

type Queries_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type queriesServicePingPong struct {
	stream client.Stream
}

func (x *queriesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *queriesServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *queriesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *queriesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *queriesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *queriesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Queries service

type QueriesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Queries_StreamStream) error
	PingPong(context.Context, Queries_PingPongStream) error
}

func RegisterQueriesHandler(s server.Server, hdlr QueriesHandler, opts ...server.HandlerOption) error {
	type queries interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Queries struct {
		queries
	}
	h := &queriesHandler{hdlr}
	return s.Handle(s.NewHandler(&Queries{h}, opts...))
}

type queriesHandler struct {
	QueriesHandler
}

func (h *queriesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.QueriesHandler.Call(ctx, in, out)
}

func (h *queriesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.QueriesHandler.Stream(ctx, m, &queriesStreamStream{stream})
}

type Queries_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type queriesStreamStream struct {
	stream server.Stream
}

func (x *queriesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *queriesStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *queriesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *queriesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *queriesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *queriesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.QueriesHandler.PingPong(ctx, &queriesPingPongStream{stream})
}

type Queries_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type queriesPingPongStream struct {
	stream server.Stream
}

func (x *queriesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *queriesPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *queriesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *queriesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *queriesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *queriesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
