// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/accounts/accounts.proto

package go_micro_service_accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Accounts service

func NewAccountsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Accounts service

type AccountsService interface {
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Accounts_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Accounts_PingPongService, error)
}

type accountsService struct {
	c    client.Client
	name string
}

func NewAccountsService(name string, c client.Client) AccountsService {
	return &accountsService{
		c:    c,
		name: name,
	}
}

func (c *accountsService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Accounts.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Accounts_StreamService, error) {
	req := c.c.NewRequest(c.name, "Accounts.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &accountsServiceStream{stream}, nil
}

type Accounts_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type accountsServiceStream struct {
	stream client.Stream
}

func (x *accountsServiceStream) Close() error {
	return x.stream.Close()
}

func (x *accountsServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *accountsServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountsServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountsServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountsService) PingPong(ctx context.Context, opts ...client.CallOption) (Accounts_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Accounts.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &accountsServicePingPong{stream}, nil
}

type Accounts_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type accountsServicePingPong struct {
	stream client.Stream
}

func (x *accountsServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *accountsServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *accountsServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountsServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountsServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *accountsServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Accounts service

type AccountsHandler interface {
	Create(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Accounts_StreamStream) error
	PingPong(context.Context, Accounts_PingPongStream) error
}

func RegisterAccountsHandler(s server.Server, hdlr AccountsHandler, opts ...server.HandlerOption) error {
	type accounts interface {
		Create(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Accounts struct {
		accounts
	}
	h := &accountsHandler{hdlr}
	return s.Handle(s.NewHandler(&Accounts{h}, opts...))
}

type accountsHandler struct {
	AccountsHandler
}

func (h *accountsHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.AccountsHandler.Create(ctx, in, out)
}

func (h *accountsHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AccountsHandler.Stream(ctx, m, &accountsStreamStream{stream})
}

type Accounts_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type accountsStreamStream struct {
	stream server.Stream
}

func (x *accountsStreamStream) Close() error {
	return x.stream.Close()
}

func (x *accountsStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *accountsStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountsStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountsStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *accountsHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AccountsHandler.PingPong(ctx, &accountsPingPongStream{stream})
}

type Accounts_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type accountsPingPongStream struct {
	stream server.Stream
}

func (x *accountsPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *accountsPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *accountsPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountsPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountsPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *accountsPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
